name: RSS Translate Notify

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache processed.json
        uses: actions/cache@v3
        with:
          path: processed.json
          key: rss-processed-cache
          restore-keys: |
            rss-processed-cache

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install feedparser argostranslate bs4

      - name: Run RSS Translate & Email
        env:
          RSS_URLS: ${{ vars.RSS_URLS }} #RSS地址逗号间隔
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python rss_translate_smtp.py
